---
properties:
  cf_mysql:
    mysql:
      port: 13306
      startup_timeout: 300
      galera_healthcheck:
        endpoint_username: galera_healthcheck_bootstrap_user
      max_open_files: 1500
    proxy:
      api_force_https: false
      api_username: 'mysql_proxy'
      healthcheck_timeout_millis: 30000
  encryption:
    active_key_label: smorgasbrod
  fissile:
    monit:
      user: admin
      port: 2289
  uaa:
    jwt:
      policy:
        active_key_id: default
    logging_level: INFO
  uaadb:
    address: database-set
    databases:
    - name: uaadb
      tag: uaa
    db_scheme: mysql
    port: 3306
